title: "Span categorization for a resume certification section."
description: "This project uses spaCy span categorizer to categorize certification section entities to 4 classes (CERTIFICATE, ORG, DATE, LOC)"

vars:
  name: "certification_span_categorizer"
  version: "0.1.0"
  lang: "fr"
  config: "default"

directories: ["assets", "corpus", "scripts", "config", "training"]

workflows:
  all:
    - preprocess
    - train
commands:
  - name: preprocess
    help: "Convert data/corpus to spaCy format"
    script:
      - "python scripts/convert.py"
    deps:
      - "assets/train.json"
      - "assets/val.json"
    outputs_no_cache:
      - "corpus/train.spacy"
      - "corpus/val.spacy"

  - name: train
    help: "Train spaCy pipline"
    script:
      - "python -m spacy train ./config/${vars.config}.cfg -o ./training/${vars.config}"
    deps:
      - "corpus/train.spacy"
      - "corpus/val.spacy"
      - "./config/${vars.config}.cfg"
    outputs:
      - "training/${vars.config}/model-best"

  - name: clean
    help: "Remove intermediate files"
    script:
      - "rm -rf training/*"
      - "rm -rf corpus/*"